// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD94wTzd2LLAmyGjAPTIeSbgbYIJ9iK9Ww',
    appId: '1:204620110750:web:73cc5f2c4e05cd78c7548f',
    messagingSenderId: '204620110750',
    projectId: 'clientsarchiev',
    authDomain: 'clientsarchiev.firebaseapp.com',
    storageBucket: 'clientsarchiev.appspot.com',
    measurementId: 'G-MNZLXWN7ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-e2F-W1HNBC8M2WgiDfN8KJRmIe0jwfM',
    appId: '1:204620110750:android:d381f18e43080957c7548f',
    messagingSenderId: '204620110750',
    projectId: 'clientsarchiev',
    storageBucket: 'clientsarchiev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdVCVW-UGpFtZZk7F6ymbXycMJoM4Fjzs',
    appId: '1:204620110750:ios:44d35cc2fc5677b6c7548f',
    messagingSenderId: '204620110750',
    projectId: 'clientsarchiev',
    storageBucket: 'clientsarchiev.appspot.com',
    iosBundleId: 'com.example.clientsArchiev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdVCVW-UGpFtZZk7F6ymbXycMJoM4Fjzs',
    appId: '1:204620110750:ios:44d35cc2fc5677b6c7548f',
    messagingSenderId: '204620110750',
    projectId: 'clientsarchiev',
    storageBucket: 'clientsarchiev.appspot.com',
    iosBundleId: 'com.example.clientsArchiev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD94wTzd2LLAmyGjAPTIeSbgbYIJ9iK9Ww',
    appId: '1:204620110750:web:9df2b3bdb2471b7cc7548f',
    messagingSenderId: '204620110750',
    projectId: 'clientsarchiev',
    authDomain: 'clientsarchiev.firebaseapp.com',
    storageBucket: 'clientsarchiev.appspot.com',
    measurementId: 'G-MX40YJTC2V',
  );
}
